name: 'All tests'
on: [pull_request, push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install valgrind
      run: sudo apt-get install -y valgrind
    - name: Install googletest
      run: sudo apt-get install -y googletest
    - name: Config
      run: sh config.sh
